# Generated by Django 5.0 on 2023-12-14 09:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_rename_signd_date_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=32)),
                ('art_name', models.CharField(max_length=32)),
                ('location', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
