# Generated by Django 5.0 on 2023-12-21 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedartist',
            name='soozan_score',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='derivedartist',
            name='validity',
            field=models.BooleanField(default=False),
        ),
    ]
