# Generated by Django 5.0 on 2023-12-24 16:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0002_derivedartist_soozan_score_derivedartist_validity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DerivedArtist',
            new_name='Artist',
        ),
    ]
