# Generated by Django 5.0 on 2023-12-24 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0003_rename_derivedartist_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='location',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)]),
        ),
    ]
