# Generated by Django 5.0 on 2023-12-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='signd_date',
            new_name='date_joined',
        ),
    ]
