# Generated by Django 5.0 on 2023-12-22 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_signd_date_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
