# Generated by Django 5.0 on 2023-12-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('number', models.CharField(max_length=11, unique=True)),
                ('user_type', models.CharField(choices=[('USER', 'User'), ('ARTIST', 'Artist')], default='USER', max_length=6)),
                ('signd_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
