# Generated by Django 5.0 on 2024-01-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
