# Generated by Django 5.0 on 2024-03-10 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name_fa',
        ),
    ]
